### ISSUE TITLE
switch from Rmd to qmd and from latex PDF to Typst

### ISSUE THREAD

**Issue by e-kotov** [Population-Dynamics-Lab/life-tables#2]
We might consider renaming the `Rmd` file to `qmd` and changing the format to Typst PDF.

As of right now, it is impossible to render the PDF from `Rmd` file inside the container. See the error below:

![Image](https://github.com/user-attachments/assets/030aeb55-ae2b-40e1-81fb-4b727b9a6db6)

If we rename the file to qmd and change header from:

```yaml
output: 
  pdf_document:
    number_sections: true
    toc: true
```

to

```yaml
format: 
  typst:
    number_sections: true
    toc: true
```

This solves the problem. Instead of "Knit" button, RStudio in the container will display the "Render" button, which uses Quarto and Typst that are preinstalled in the container. They produce a PDF without any issues, and also this PDF is better in that it has automatic line breaks for long code lines.

That is, instead of this:

![Image](https://github.com/user-attachments/assets/3ee4a68c-ffe5-4d39-9bce-1a44fc556bc6)

We get this:

![Image](https://github.com/user-attachments/assets/07ca3f23-8d5c-428b-a065-8985cb3b9c1d)

@jlgodwin @krpaulson I can make a PR to do that, if that's ok.
